services:
  - type: web
    name: vikasatarangini
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 5050
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GMAIL_USER
        value: vikasatarangini4@gmail.com
      - key: GMAIL_PASS
        value: "cljt mwaq ktob dodw"
