services:
  - type: web
    name: vikasatarangini
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5050
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_TEMPLATE_NAME
        value: hello_world
      - key: CLIENT_ORIGIN
        sync: false
